title: "Mohammed Nowaz Rabbani Chowdhury"
description: "Ph.D. Candidate in Electrical Engineering at RPI"

# IMPORTANT: use remote_theme, NOT theme
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: False

# Optional sidebar logo
logo: "/assets/profile.jpg"

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Navigation for collections
just_the_docs:
  collections:
    projects:
      name: "Research Projects"
      nav_order: 3
    publications:
      name: "Publications"
      nav_order: 4
