title: "Mohammed Nowaz Rabbani Chowdhury"
description: "Ph.D. Candidate in Electrical Engineering at RPI"

theme: "just-the-docs"

# Enable search bar
search_enabled: true

# Sidebar logo (optional)
just_the_docs:
  logo: "/assets/profile.jpg"   # remove if you don't want a photo in sidebar

# Collections for your publications & research projects
collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Make collections appear in sidebar
just_the_docs:
  collections:
    publications:
      name: "Publications"
      nav_order: 4
    projects:
      name: "Research Projects"
      nav_order: 3
